import { Inter } from "@next/font/google";
import HelloSection from "../Components/Home/HelloSection";
import Head from "next/head";
import Facilities from "../Components/Home/Facilities/Facilities";
import Contacts from "../Components/Home/Contacts";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Super Hostel Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-orange-50 text-black">
        <HelloSection />
        <Facilities />
        <Contacts />
      </div>
    </>
  );
}
